# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: location.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0elocation.proto\x12\x05greet\"u\n\x0fLocationMessage\x12\x11\n\tperson_id\x18\x01 \x01(\x05\x12\x13\n\x0bperson_name\x18\x02 \x01(\t\x12\x11\n\tlongitude\x18\x03 \x01(\t\x12\x10\n\x08latitude\x18\x04 \x01(\t\x12\x15\n\rcreation_time\x18\x05 \x01(\t\"\x07\n\x05\x45mpty\"@\n\x13LocationMessageList\x12)\n\tlocations\x18\x01 \x03(\x0b\x32\x16.greet.LocationMessage2Q\n\x08Location\x12\x45\n\x0fLocationCheckIn\x12\x16.greet.LocationMessage\x1a\x16.greet.LocationMessage(\x01\x30\x01\x32|\n\x0fLocationService\x12\x38\n\x06\x43reate\x12\x16.greet.LocationMessage\x1a\x16.greet.LocationMessage\x12/\n\x03Get\x12\x0c.greet.Empty\x1a\x1a.greet.LocationMessageListb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'location_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _LOCATIONMESSAGE._serialized_start=25
  _LOCATIONMESSAGE._serialized_end=142
  _EMPTY._serialized_start=144
  _EMPTY._serialized_end=151
  _LOCATIONMESSAGELIST._serialized_start=153
  _LOCATIONMESSAGELIST._serialized_end=217
  _LOCATION._serialized_start=219
  _LOCATION._serialized_end=300
  _LOCATIONSERVICE._serialized_start=302
  _LOCATIONSERVICE._serialized_end=426
# @@protoc_insertion_point(module_scope)
