apiVersion: v1
kind: ConfigMap
data:
  DB_USERNAME: "ct_admin"
  DB_NAME: "geoconnections"
  DB_HOST: "postgres"
  DB_PORT: "5432"
  KAFKA_SERVER: "kafka-headless:9092"
  GRPC_SERVER: "udaconnect-notifications-service:30050"
  SKIP_PREFLIGHT_CHECK: "true"
  REACT_APP_WS_URL: "http://167.235.227.66/:30005/locationCheckin"
metadata:
  name: db-env
  namespace: {{ .Values.namespace.name }}