apiVersion: v1
kind: Service
metadata:
  namespace: {{ .Values.namespace.name }}
  labels:
    service: udaconnect-app
  name: udaconnect-app
spec:
  ports:
  - name: "3000"
    port: 3000
    targetPort: 3000
    nodePort: 30000
  selector:
    service: udaconnect-app
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: {{ .Values.namespace.name }}
  labels:
    service: udaconnect-app
  name: udaconnect-app
spec:
  replicas: 1
  selector:
    matchLabels:
      service: udaconnect-app
  template:
    metadata:
      labels:
        service: udaconnect-app
    spec:
      containers:
      - image: hosamelbasiony/udaconnect-app:v1.5.2
        name: udaconnect-app
        imagePullPolicy: Always
        env:
          - name: SKIP_PREFLIGHT_CHECK
            valueFrom:
              configMapKeyRef:
                name: db-env
                key: SKIP_PREFLIGHT_CHECK
          - name: REACT_APP_WS_URL
            valueFrom:
              configMapKeyRef:
                name: db-env
                key: REACT_APP_WS_URL
          - name: REACT_APP_LOCATIONS_API_URL
            value: "http://http://167.235.227.66/:30004/api"
        resources:
          requests:
            memory: "1024Mi"
            cpu: "256m"
          limits:
            memory: "1024Mi"
            cpu: "512m"
      restartPolicy: Always
